allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  cloudflared: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@apps-in-toss/cli@2.10.8'
  - '@apps-in-toss/web-framework@2.10.8'
